---
title: "HW 04 - Model and review"
author: "Myles Douglas"
date: "16/11/2022"
output: html_document
---

```{r load-packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
```


```{r eval=FALSE}

gss16<-read_csv( "gss16.csv")
```


### Ex. 1. a)

#### Code

```{r eval=TRUE}

gss16 <- gss16 %>%
  mutate(
    advfront = case_when(
     advfront == "Agree" ~ "Agree",
     advfront == "Strongly agree" ~ "Agree",
     advfront == "Disagree" ~ "Not agree",
     advfront == "Dont know" ~ "Not agree",
     advfront == "Strongly disagree" ~ "Not agree"
    ),
    advfront = fct_relevel(advfront, "Not agree", "Agree ")
  )

gss16 %>%
  count(advfront)
```

### Ex. 1. b)

#### Code

```{r}
gss16 <- gss16 %>%
  mutate(
    polviews = case_when(
     polviews == "Moderate" ~ "Moderate",
     polviews == "Conservative" ~ "Conservative",
     polviews == "Extrmly conservative" ~ "Conservative",
     polviews == "slghtly conservative" ~ "Conservative",
     polviews == "Slightly liberal" ~ "Liberal",
     polviews == "Extremely liberal" ~ "Liberal",
     polviews == "Liberal" ~ "Liberal"
    ),
    polviews = fct_relevel(polviews, "Conservative", "Moderate ", "Liberal" )
  )

gss16 %>%
  count(polviews)
```

### Ex. 1. c)

#### Code

```{r eval=TRUE}
# change eval=FALSE to eval=TRUE

gss16_advfront <- gss16 %>%
  select(advfront, educ, polviews, wrkstat) %>%
  drop_na()
print (gss16_advfront)
```


### Ex. 2

### Split into training and test set

```{r split-data, eval=TRUE}
# change eval=FALSE to eval=TRUE

set.seed(1234)
gss16_split <- initial_split(gss16_advfront)
gss16_train <- training(gss16_split)
gss16_test  <- testing(gss16_split)
```


#### Recipe

```{r eval=TRUE}
# change eval=FALSE to eval=TRUE

gss16_rec_1 <- recipe(advfront ~ . , data = gss16_advfront) %>%
  step_other(wrkstat, threshold = 0.1, other = "workstat") %>%
  step_dummy(all_nominal(), all_outcomes())
```

#### Model 

```{r eval=TRUE}
# change eval=FALSE to eval=TRUE
gss16_spec_1 <- logistic_reg() %>% 
  set_engine("glm")


```

#### Workflow

```{r eval=TRUE}
# change eval=FALSE to eval=TRUE
gss16_wflow_1 <- workflow() %>% 
  add_model(gss16_spec_1) %>% 
  add_recipe(gss16_rec_1) %>%
  print()

```

#### Narrative

*Add your narrative here.*

### Ex. 3. a)

#### Code

```{r eval=TRUE}
# change eval=FALSE to eval=TRUE

gss16_fit_1 <- gss16_wflow_1 %>% 
  fit(data = gss16_train) 

gss16_fit_1 %>% print()
 
```

### Ex. 3. b)

#### Code

```{r eval=FALSE}
# change eval=FALSE to eval=TRUE


```


### Ex. 3. c)

#### Narrative

*Add your narrative here.*


### Ex. 4

#### Code

```{r}

```

#### Narrative

*Add your narrative here.*

